name: Auto Rebase from Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/stackblitz/bolt.new.git
          git fetch upstream

      - name: Rebase upstream changes onto fork
        run: |
          git checkout main
          git rebase upstream/main || git rebase --abort
          
      - name: Push changes back to fork
        run: |
          git push origin main --force